Config_Dict = {
    "judgerName": "Rikka",
    "server": "http://127.0.0.1:10567",
    "serverFetchUser": "http://127.0.0.1:10430/fetchRepo",
    "serverFetchTask": "http://127.0.0.1:10430/fetchTask",
    "serverSubmitTask": "http://127.0.0.1:10430/submitTask",
    "serverFetchCompileTask": "http://127.0.0.1:10430/fetchBuild",
    "serverSubmitCompileTask": "http://127.0.0.1:10430/submitBuild",
    "dockerbase": "compilerBase",
    "dockerprefix": "cdocker_",
    "dockerfilepath": "../dockerfile/",
    "dockerbasepath": "../dockerfile/Base/",
    "sqladdress": "127.0.0.1",
    "sqlport": 3310,
    "sqlname": "abcdabcd",
    "sqlword": "abcdabcd",
    "sqltable": "compiler_data",
    "dataPath": "/home/judge/data/",
    "compilerPath" : "/home/judge/compiler",
    "compilerBackupPath": "/home/judge/compiler_backup",
    "GitTimeout": 30,
    "MaxlogSize": 4096,
    "RavelExecutable" : "/home/judge/ravel/bin/ravel",
    "RavelPath": "/home/judge/ravel/bin"
}
